package com.card.management.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.card.management.entity.MBatchNumber;
import com.card.management.entity.MBatchNumberExample;

@Mapper
public interface MBatchNumberMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	
	long countByExample(MBatchNumberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int deleteByExample(MBatchNumberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int insert(MBatchNumber row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int insertSelective(MBatchNumber row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	List<MBatchNumber> selectByExample(MBatchNumberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	MBatchNumber selectByPrimaryKey(Integer id);
	
	MBatchNumber selectByBatchNumber(String BatchNumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int updateByExampleSelective(@Param("row") MBatchNumber row, @Param("example") MBatchNumberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int updateByExample(@Param("row") MBatchNumber row, @Param("example") MBatchNumberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int updateByPrimaryKeySelective(MBatchNumber row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table m_batch_number
	 * @mbg.generated  Thu Feb 29 20:48:52 CST 2024
	 */
	int updateByPrimaryKey(MBatchNumber row);
}