package com.card.management.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.card.management.entity.AssembleDetailEntity;
import com.card.management.entity.TAssembleDetail;
import com.card.management.entity.TAssembleDetailExample;

@Mapper
public interface TAssembleDetailMapper {
	List<AssembleDetailEntity> selectAssembleDetailBybatchNumber(String batchNumber);

	long selectAssembleDetailCount(String batchNumber);
	
	long insertAssembleDetail(List<TAssembleDetail> assembleDetailList);
	
	long insert(TAssembleDetail assembleDetail);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Tue Mar 12 22:53:59 CST 2024
	 */
	int updateByExampleSelective(@Param("row") TAssembleDetail row, @Param("example") TAssembleDetailExample example);
	
	int clearAssembleDetail(List<String> cardBindingNumberList);
	
	List<TAssembleDetail> selectByExample(TAssembleDetailExample example);
}