package com.card.management.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.card.management.entity.TBatchProcessResultConfirm;
import com.card.management.entity.TBatchProcessResultConfirmExample;

@Mapper
public interface TBatchProcessResultConfirmMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	long countByExample(TBatchProcessResultConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int deleteByExample(TBatchProcessResultConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int insert(TBatchProcessResultConfirm row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int insertSelective(TBatchProcessResultConfirm row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	List<TBatchProcessResultConfirm> selectByExample(TBatchProcessResultConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	TBatchProcessResultConfirm selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int updateByExampleSelective(@Param("row") TBatchProcessResultConfirm row,
			@Param("example") TBatchProcessResultConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int updateByExample(@Param("row") TBatchProcessResultConfirm row,
			@Param("example") TBatchProcessResultConfirmExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int updateByPrimaryKeySelective(TBatchProcessResultConfirm row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_batch_process_result_confirm
	 * @mbg.generated  Thu Mar 21 00:18:21 CST 2024
	 */
	int updateByPrimaryKey(TBatchProcessResultConfirm row);
}