package com.card.management.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.card.management.entity.PreparatoryDetailEntity;
import com.card.management.entity.TPreparatoryDetail;

@Mapper
public interface TPreparatoryDetailMapper {
	
	List<PreparatoryDetailEntity> selectPreparatoryDetailBybatchNumber(String batchNumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_preparatory_detail
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	long selectPreparatoryDetailCount(String  batchNumber);
	
	long insertPreparatory(List<TPreparatoryDetail> tdList);
	
	int clearPreparatoryDetail(List<String> cardBindingNumberList);
	
	List<PreparatoryDetailEntity> checkPreparatoryBinNumber(List<String> cardBindingNumberList);

}