package com.card.management.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TAssembleDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public TAssembleDetailExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBatchNumberIsNull() {
			addCriterion("batch_number is null");
			return (Criteria) this;
		}

		public Criteria andBatchNumberIsNotNull() {
			addCriterion("batch_number is not null");
			return (Criteria) this;
		}

		public Criteria andBatchNumberEqualTo(String value) {
			addCriterion("batch_number =", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberNotEqualTo(String value) {
			addCriterion("batch_number <>", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberGreaterThan(String value) {
			addCriterion("batch_number >", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberGreaterThanOrEqualTo(String value) {
			addCriterion("batch_number >=", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberLessThan(String value) {
			addCriterion("batch_number <", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberLessThanOrEqualTo(String value) {
			addCriterion("batch_number <=", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberLike(String value) {
			addCriterion("batch_number like", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberNotLike(String value) {
			addCriterion("batch_number not like", value, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberIn(List<String> values) {
			addCriterion("batch_number in", values, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberNotIn(List<String> values) {
			addCriterion("batch_number not in", values, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberBetween(String value1, String value2) {
			addCriterion("batch_number between", value1, value2, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andBatchNumberNotBetween(String value1, String value2) {
			addCriterion("batch_number not between", value1, value2, "batchNumber");
			return (Criteria) this;
		}

		public Criteria andWriteDateIsNull() {
			addCriterion("write_date is null");
			return (Criteria) this;
		}

		public Criteria andWriteDateIsNotNull() {
			addCriterion("write_date is not null");
			return (Criteria) this;
		}

		public Criteria andWriteDateEqualTo(Date value) {
			addCriterionForJDBCDate("write_date =", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("write_date <>", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateGreaterThan(Date value) {
			addCriterionForJDBCDate("write_date >", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("write_date >=", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateLessThan(Date value) {
			addCriterionForJDBCDate("write_date <", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("write_date <=", value, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateIn(List<Date> values) {
			addCriterionForJDBCDate("write_date in", values, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("write_date not in", values, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("write_date between", value1, value2, "writeDate");
			return (Criteria) this;
		}

		public Criteria andWriteDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("write_date not between", value1, value2, "writeDate");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberIsNull() {
			addCriterion("card_binding_number is null");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberIsNotNull() {
			addCriterion("card_binding_number is not null");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberEqualTo(String value) {
			addCriterion("card_binding_number =", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberNotEqualTo(String value) {
			addCriterion("card_binding_number <>", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberGreaterThan(String value) {
			addCriterion("card_binding_number >", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberGreaterThanOrEqualTo(String value) {
			addCriterion("card_binding_number >=", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberLessThan(String value) {
			addCriterion("card_binding_number <", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberLessThanOrEqualTo(String value) {
			addCriterion("card_binding_number <=", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberLike(String value) {
			addCriterion("card_binding_number like", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberNotLike(String value) {
			addCriterion("card_binding_number not like", value, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberIn(List<String> values) {
			addCriterion("card_binding_number in", values, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberNotIn(List<String> values) {
			addCriterion("card_binding_number not in", values, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberBetween(String value1, String value2) {
			addCriterion("card_binding_number between", value1, value2, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andCardBindingNumberNotBetween(String value1, String value2) {
			addCriterion("card_binding_number not between", value1, value2, "cardBindingNumber");
			return (Criteria) this;
		}

		public Criteria andTicketInfoIsNull() {
			addCriterion("ticket_info is null");
			return (Criteria) this;
		}

		public Criteria andTicketInfoIsNotNull() {
			addCriterion("ticket_info is not null");
			return (Criteria) this;
		}

		public Criteria andTicketInfoEqualTo(String value) {
			addCriterion("ticket_info =", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoNotEqualTo(String value) {
			addCriterion("ticket_info <>", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoGreaterThan(String value) {
			addCriterion("ticket_info >", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoGreaterThanOrEqualTo(String value) {
			addCriterion("ticket_info >=", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoLessThan(String value) {
			addCriterion("ticket_info <", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoLessThanOrEqualTo(String value) {
			addCriterion("ticket_info <=", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoLike(String value) {
			addCriterion("ticket_info like", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoNotLike(String value) {
			addCriterion("ticket_info not like", value, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoIn(List<String> values) {
			addCriterion("ticket_info in", values, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoNotIn(List<String> values) {
			addCriterion("ticket_info not in", values, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoBetween(String value1, String value2) {
			addCriterion("ticket_info between", value1, value2, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andTicketInfoNotBetween(String value1, String value2) {
			addCriterion("ticket_info not between", value1, value2, "ticketInfo");
			return (Criteria) this;
		}

		public Criteria andAssembleResultIsNull() {
			addCriterion("assemble_result is null");
			return (Criteria) this;
		}

		public Criteria andAssembleResultIsNotNull() {
			addCriterion("assemble_result is not null");
			return (Criteria) this;
		}

		public Criteria andAssembleResultEqualTo(String value) {
			addCriterion("assemble_result =", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultNotEqualTo(String value) {
			addCriterion("assemble_result <>", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultGreaterThan(String value) {
			addCriterion("assemble_result >", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultGreaterThanOrEqualTo(String value) {
			addCriterion("assemble_result >=", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultLessThan(String value) {
			addCriterion("assemble_result <", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultLessThanOrEqualTo(String value) {
			addCriterion("assemble_result <=", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultLike(String value) {
			addCriterion("assemble_result like", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultNotLike(String value) {
			addCriterion("assemble_result not like", value, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultIn(List<String> values) {
			addCriterion("assemble_result in", values, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultNotIn(List<String> values) {
			addCriterion("assemble_result not in", values, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultBetween(String value1, String value2) {
			addCriterion("assemble_result between", value1, value2, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andAssembleResultNotBetween(String value1, String value2) {
			addCriterion("assemble_result not between", value1, value2, "assembleResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultIsNull() {
			addCriterion("ground_connection_result is null");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultIsNotNull() {
			addCriterion("ground_connection_result is not null");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultEqualTo(String value) {
			addCriterion("ground_connection_result =", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultNotEqualTo(String value) {
			addCriterion("ground_connection_result <>", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultGreaterThan(String value) {
			addCriterion("ground_connection_result >", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultGreaterThanOrEqualTo(String value) {
			addCriterion("ground_connection_result >=", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultLessThan(String value) {
			addCriterion("ground_connection_result <", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultLessThanOrEqualTo(String value) {
			addCriterion("ground_connection_result <=", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultLike(String value) {
			addCriterion("ground_connection_result like", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultNotLike(String value) {
			addCriterion("ground_connection_result not like", value, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultIn(List<String> values) {
			addCriterion("ground_connection_result in", values, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultNotIn(List<String> values) {
			addCriterion("ground_connection_result not in", values, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultBetween(String value1, String value2) {
			addCriterion("ground_connection_result between", value1, value2, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andGroundConnectionResultNotBetween(String value1, String value2) {
			addCriterion("ground_connection_result not between", value1, value2, "groundConnectionResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultIsNull() {
			addCriterion("withstand_voltage_result is null");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultIsNotNull() {
			addCriterion("withstand_voltage_result is not null");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultEqualTo(String value) {
			addCriterion("withstand_voltage_result =", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultNotEqualTo(String value) {
			addCriterion("withstand_voltage_result <>", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultGreaterThan(String value) {
			addCriterion("withstand_voltage_result >", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultGreaterThanOrEqualTo(String value) {
			addCriterion("withstand_voltage_result >=", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultLessThan(String value) {
			addCriterion("withstand_voltage_result <", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultLessThanOrEqualTo(String value) {
			addCriterion("withstand_voltage_result <=", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultLike(String value) {
			addCriterion("withstand_voltage_result like", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultNotLike(String value) {
			addCriterion("withstand_voltage_result not like", value, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultIn(List<String> values) {
			addCriterion("withstand_voltage_result in", values, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultNotIn(List<String> values) {
			addCriterion("withstand_voltage_result not in", values, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultBetween(String value1, String value2) {
			addCriterion("withstand_voltage_result between", value1, value2, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andWithstandVoltageResultNotBetween(String value1, String value2) {
			addCriterion("withstand_voltage_result not between", value1, value2, "withstandVoltageResult");
			return (Criteria) this;
		}

		public Criteria andUtResultIsNull() {
			addCriterion("ut_result is null");
			return (Criteria) this;
		}

		public Criteria andUtResultIsNotNull() {
			addCriterion("ut_result is not null");
			return (Criteria) this;
		}

		public Criteria andUtResultEqualTo(String value) {
			addCriterion("ut_result =", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultNotEqualTo(String value) {
			addCriterion("ut_result <>", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultGreaterThan(String value) {
			addCriterion("ut_result >", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultGreaterThanOrEqualTo(String value) {
			addCriterion("ut_result >=", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultLessThan(String value) {
			addCriterion("ut_result <", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultLessThanOrEqualTo(String value) {
			addCriterion("ut_result <=", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultLike(String value) {
			addCriterion("ut_result like", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultNotLike(String value) {
			addCriterion("ut_result not like", value, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultIn(List<String> values) {
			addCriterion("ut_result in", values, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultNotIn(List<String> values) {
			addCriterion("ut_result not in", values, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultBetween(String value1, String value2) {
			addCriterion("ut_result between", value1, value2, "utResult");
			return (Criteria) this;
		}

		public Criteria andUtResultNotBetween(String value1, String value2) {
			addCriterion("ut_result not between", value1, value2, "utResult");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_assemble_detail
	 * @mbg.generated  Sat Mar 09 12:18:20 CST 2024
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_assemble_detail
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 09 12:18:20 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}