package com.card.management.entity;

import java.util.Date;

public class TBatchProcessResultConfirm {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.id
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.batch_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private String batchNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.write_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Date writeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.car_times
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Byte carTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.card_binding_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private String cardBindingNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.project_category
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private String projectCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.check_result
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Boolean checkResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.update_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_batch_process_result_confirm.create_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.id
	 * @return  the value of t_batch_process_result_confirm.id
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.id
	 * @param id  the value for t_batch_process_result_confirm.id
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.batch_number
	 * @return  the value of t_batch_process_result_confirm.batch_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public String getBatchNumber() {
		return batchNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.batch_number
	 * @param batchNumber  the value for t_batch_process_result_confirm.batch_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber == null ? null : batchNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.write_date
	 * @return  the value of t_batch_process_result_confirm.write_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Date getWriteDate() {
		return writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.write_date
	 * @param writeDate  the value for t_batch_process_result_confirm.write_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.car_times
	 * @return  the value of t_batch_process_result_confirm.car_times
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Byte getCarTimes() {
		return carTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.car_times
	 * @param carTimes  the value for t_batch_process_result_confirm.car_times
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setCarTimes(Byte carTimes) {
		this.carTimes = carTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.card_binding_number
	 * @return  the value of t_batch_process_result_confirm.card_binding_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public String getCardBindingNumber() {
		return cardBindingNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.card_binding_number
	 * @param cardBindingNumber  the value for t_batch_process_result_confirm.card_binding_number
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setCardBindingNumber(String cardBindingNumber) {
		this.cardBindingNumber = cardBindingNumber == null ? null : cardBindingNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.project_category
	 * @return  the value of t_batch_process_result_confirm.project_category
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public String getProjectCategory() {
		return projectCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.project_category
	 * @param projectCategory  the value for t_batch_process_result_confirm.project_category
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setProjectCategory(String projectCategory) {
		this.projectCategory = projectCategory == null ? null : projectCategory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.check_result
	 * @return  the value of t_batch_process_result_confirm.check_result
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Boolean getCheckResult() {
		return checkResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.check_result
	 * @param checkResult  the value for t_batch_process_result_confirm.check_result
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setCheckResult(Boolean checkResult) {
		this.checkResult = checkResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.update_date
	 * @return  the value of t_batch_process_result_confirm.update_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.update_date
	 * @param updateDate  the value for t_batch_process_result_confirm.update_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_batch_process_result_confirm.create_date
	 * @return  the value of t_batch_process_result_confirm.create_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_batch_process_result_confirm.create_date
	 * @param createDate  the value for t_batch_process_result_confirm.create_date
	 * @mbg.generated  Sat Mar 09 14:55:54 CST 2024
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}