package com.card.management.entity;

import java.util.Date;

public class TLoGradeHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.id
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.batch_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String batchNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.machine_category_name
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String machineCategoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.write_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String writeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.card_binding_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String cardBindingNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.process_category
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String processCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.process_result
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private String processResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.update_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_lo_grade_history.create_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.id
	 * @return  the value of t_lo_grade_history.id
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.id
	 * @param id  the value for t_lo_grade_history.id
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.batch_number
	 * @return  the value of t_lo_grade_history.batch_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getBatchNumber() {
		return batchNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.batch_number
	 * @param batchNumber  the value for t_lo_grade_history.batch_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber == null ? null : batchNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.machine_category_name
	 * @return  the value of t_lo_grade_history.machine_category_name
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getMachineCategoryName() {
		return machineCategoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.machine_category_name
	 * @param machineCategoryName  the value for t_lo_grade_history.machine_category_name
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setMachineCategoryName(String machineCategoryName) {
		this.machineCategoryName = machineCategoryName == null ? null : machineCategoryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.write_date
	 * @return  the value of t_lo_grade_history.write_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getWriteDate() {
		return writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.write_date
	 * @param writeDate  the value for t_lo_grade_history.write_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setWriteDate(String writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.card_binding_number
	 * @return  the value of t_lo_grade_history.card_binding_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getCardBindingNumber() {
		return cardBindingNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.card_binding_number
	 * @param cardBindingNumber  the value for t_lo_grade_history.card_binding_number
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setCardBindingNumber(String cardBindingNumber) {
		this.cardBindingNumber = cardBindingNumber == null ? null : cardBindingNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.process_category
	 * @return  the value of t_lo_grade_history.process_category
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getProcessCategory() {
		return processCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.process_category
	 * @param processCategory  the value for t_lo_grade_history.process_category
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setProcessCategory(String processCategory) {
		this.processCategory = processCategory == null ? null : processCategory.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.process_result
	 * @return  the value of t_lo_grade_history.process_result
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public String getProcessResult() {
		return processResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.process_result
	 * @param processResult  the value for t_lo_grade_history.process_result
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setProcessResult(String processResult) {
		this.processResult = processResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.update_date
	 * @return  the value of t_lo_grade_history.update_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.update_date
	 * @param updateDate  the value for t_lo_grade_history.update_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_lo_grade_history.create_date
	 * @return  the value of t_lo_grade_history.create_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_lo_grade_history.create_date
	 * @param createDate  the value for t_lo_grade_history.create_date
	 * @mbg.generated  Sat Mar 09 16:26:40 CST 2024
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}