package com.card.management.entity;

import java.util.Date;

public class TPreparatoryDetail {
	private String checkResult;
	
	public String getCheckResult() {
		return checkResult;
	}

	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult == null ? null : checkResult.trim();
	}
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.id
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.batch_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private String batchNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.write_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private Date writeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.car_times
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private int carTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.card_binding_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private String cardBindingNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.update_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_preparatory_detail.create_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.id
	 * @return  the value of t_preparatory_detail.id
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.id
	 * @param id  the value for t_preparatory_detail.id
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.batch_number
	 * @return  the value of t_preparatory_detail.batch_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public String getBatchNumber() {
		return batchNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.batch_number
	 * @param batchNumber  the value for t_preparatory_detail.batch_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber == null ? null : batchNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.write_date
	 * @return  the value of t_preparatory_detail.write_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public Date getWriteDate() {
		return writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.write_date
	 * @param writeDate  the value for t_preparatory_detail.write_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.car_times
	 * @return  the value of t_preparatory_detail.car_times
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public int getCarTimes() {
		return carTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.car_times
	 * @param carTimes  the value for t_preparatory_detail.car_times
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setCarTimes(int carTimes) {
		this.carTimes = carTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.card_binding_number
	 * @return  the value of t_preparatory_detail.card_binding_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public String getCardBindingNumber() {
		return cardBindingNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.card_binding_number
	 * @param cardBindingNumber  the value for t_preparatory_detail.card_binding_number
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setCardBindingNumber(String cardBindingNumber) {
		this.cardBindingNumber = cardBindingNumber == null ? null : cardBindingNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.update_date
	 * @return  the value of t_preparatory_detail.update_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.update_date
	 * @param updateDate  the value for t_preparatory_detail.update_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_preparatory_detail.create_date
	 * @return  the value of t_preparatory_detail.create_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_preparatory_detail.create_date
	 * @param createDate  the value for t_preparatory_detail.create_date
	 * @mbg.generated  Sat Mar 09 08:43:52 CST 2024
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}