package com.card.management.entity;

import java.util.Date;

public class TWarningMessage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_warning_message.id
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_warning_message.batch_number
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	private String batchNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_warning_message.write_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	private Date writeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_warning_message.warning_message
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	private String warningMessage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_warning_message.create_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	private Date createDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_warning_message.id
	 * @return  the value of t_warning_message.id
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_warning_message.id
	 * @param id  the value for t_warning_message.id
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_warning_message.batch_number
	 * @return  the value of t_warning_message.batch_number
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public String getBatchNumber() {
		return batchNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_warning_message.batch_number
	 * @param batchNumber  the value for t_warning_message.batch_number
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber == null ? null : batchNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_warning_message.write_date
	 * @return  the value of t_warning_message.write_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public Date getWriteDate() {
		return writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_warning_message.write_date
	 * @param writeDate  the value for t_warning_message.write_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public void setWriteDate(Date writeDate) {
		this.writeDate = writeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_warning_message.warning_message
	 * @return  the value of t_warning_message.warning_message
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public String getWarningMessage() {
		return warningMessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_warning_message.warning_message
	 * @param warningMessage  the value for t_warning_message.warning_message
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public void setWarningMessage(String warningMessage) {
		this.warningMessage = warningMessage == null ? null : warningMessage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_warning_message.create_date
	 * @return  the value of t_warning_message.create_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_warning_message.create_date
	 * @param createDate  the value for t_warning_message.create_date
	 * @mbg.generated  Sun Mar 10 14:50:42 CST 2024
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}